name: CI/CD

on:
  push:
    branches: '**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build
    
    - name: Uploading artifact
      uses: actions/upload-artifact@v2
      with:
        name: Artifact
        path: build/

  github-package:
    if: github.ref  == 'refs/heads/master' || github.ref  == 'refs/heads/workflow' 
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download Artifact
      uses: actions/download-artifact@master
      with:
        name: Artifact
        path: build/
    - name: Login to Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.PAT_GHCR }}
    - name: Build Docker images
      env:
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_URL: ${{ secrets.DB_URL }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_DATABASE: ${{ secrets.DB_DATABASE }}
      run: |
        docker build . --rm -t ghcr.io/starsaminf/github-packages-example:latest
    - name: Push Docker images to registry
      run: |
        docker push ghcr.io/starsaminf/github-packages-example:latest
